# Generated by Django 5.2.17 on 2026-10-06 19:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable category name (e.g. Auto, Sedan, SUV)', max_length=50)),
                ('code', models.CharField(db_index=True, help_text='Unique category slug/identifier (e.g. AUTO, SEDAN, SUV)', max_length=30, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=4, help_text='Maximum passenger capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this vehicle category is offered on the platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle categories',
                'db_table': 'vehicles_category',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='vehicle_category_capacity_positive')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, help_text='Vehicle license plate / registration number (e.g. KL 07 CA 1234)', max_length=30, unique=True)),
                ('make', models.CharField(help_text='Manufacturer (e.g. Maruti Suzuki, Bajaj, Hyundai)', max_length=50)),
                ('model', models.CharField(help_text='Model name (e.g. Dzire, RE, Creta)', max_length=50)),
                ('manufacture_year', models.PositiveSmallIntegerField(help_text='Year of manufacture', validators=[django.core.validators.MinValueValidator(1990)])),
                ('capacity', models.PositiveSmallIntegerField(help_text='Seating capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Lifecycle flag. Only one active vehicle per driver is permitted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='Associated driver profile', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='drivers.driverprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclecategory')),
            ],
            options={
                'db_table': 'vehicles_vehicle',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'is_active'], name='vehicle_driver_active_idx'), models.Index(fields=['category', 'is_active'], name='vehicle_category_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('driver',), name='unique_active_vehicle_per_driver'), models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='vehicle_capacity_positive')],
            },
        ),
    ]
