# Generated by Django 5.2.17 on 2026-10-06 19:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(db_index=True, help_text='Government driving license number', max_length=50, unique=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(db_index=True, default=False, help_text='Driver online availability for hailing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved or reviewed this driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_driver_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers_driver_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('DRIVING_LICENSE', 'Driving License'), ('RC', 'Registration Certificate (RC)'), ('INSURANCE', 'Insurance Certificate'), ('IDENTITY', 'Identity Proof')], max_length=30)),
                ('document_number', models.CharField(max_length=100)),
                ('file_url', models.URLField(help_text='Object storage URL for document file', max_length=500)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True, help_text='Designates the current active version of this document type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_driver_documents', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driverprofile')),
            ],
            options={
                'db_table': 'drivers_driver_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverCurrentLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='WGS-84 latitude (-90 to +90)', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='WGS-84 longitude (-180 to +180)', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy radius in meters', max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True, help_text='Timestamp of latest GPS fix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='drivers.driverprofile')),
            ],
            options={
                'db_table': 'drivers_current_location',
            },
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['approval_status', 'is_online'], name='driver_approval_online_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['is_online'], name='driver_online_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['driver', 'review_status'], name='driver_doc_review_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['review_status', 'created_at'], name='doc_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('driver', 'document_type'), name='unique_current_driver_document'),
        ),
        migrations.AddIndex(
            model_name='drivercurrentlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='driver_loc_coords_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivercurrentlocation',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', Decimal('-90.0')), ('latitude__lte', Decimal('90.0'))), name='drivers_location_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='drivercurrentlocation',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', Decimal('-180.0')), ('longitude__lte', Decimal('180.0'))), name='drivers_location_lon_valid'),
        ),
    ]
