# Generated by Django 5.2.17 on 2026-10-06 19:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Disbursement amount in INR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, help_text='Bank payout transaction / UTR reference', max_length=150, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='drivers.driverprofile')),
            ],
            options={
                'db_table': 'payments_payout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('RIDE_EARNING', 'Ride Earning'), ('COMMISSION', 'Platform Commission'), ('ADJUSTMENT', 'Adjustment'), ('PAYOUT', 'Payout')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive amount for this entry', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='drivers.driverprofile')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='rides.ride')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.payout')),
            ],
            options={
                'db_table': 'payments_driver_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in INR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('GATEWAY', 'Online Gateway')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, help_text='Reference ID from Razorpay / Stripe / Bank', max_length=150, null=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, help_text='Unique idempotency token to prevent double-charging', unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rides.ride')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ride', 'status'], name='payment_ride_status_idx'), models.Index(fields=['status', 'created_at'], name='payment_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='payment_amount_gte_zero'), models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('ride',), name='unique_successful_payment_per_ride')],
            },
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payout_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='driverledgerentry',
            index=models.Index(fields=['driver', 'entry_type'], name='ledger_driver_type_idx'),
        ),
        migrations.AddIndex(
            model_name='driverledgerentry',
            index=models.Index(fields=['driver', 'created_at'], name='ledger_driver_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='ledger_amount_positive'),
        ),
    ]
