# Generated by Django 5.2.17 on 2026-10-06 19:05

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=20)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trip_pin_hash', models.CharField(blank=True, help_text='Hashed 4-digit start OTP / PIN verified before trip start', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('driver_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Passenger who requested the ride (must have role USER)', on_delete=django.db.models.deletion.PROTECT, related_name='customer_rides', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Driver fulfilling the ride (must have role DRIVER)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_rides', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='vehicles.vehicle')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='vehicles.vehiclecategory')),
            ],
            options={
                'db_table': 'rides_ride',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancelled_by', models.CharField(choices=[('USER', 'User'), ('DRIVER', 'Driver'), ('SYSTEM', 'System'), ('ADMIN', 'Admin')], max_length=20)),
                ('reason', models.TextField()),
                ('cancellation_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_rides', to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='rides.ride')),
            ],
            options={
                'db_table': 'rides_cancellation',
            },
        ),
        migrations.CreateModel(
            name='RideFare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('distance_charge', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration_charge', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cancellation_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gross_fare', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fare_breakdown', to='rides.ride')),
            ],
            options={
                'db_table': 'rides_fare',
            },
        ),
        migrations.CreateModel(
            name='RideLocationPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_pings', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='rides.ride')),
            ],
            options={
                'db_table': 'rides_location_ping',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RideSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_fare', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('driver_net_earnings', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='rides.ride')),
            ],
            options={
                'db_table': 'rides_settlement',
            },
        ),
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DESTINATION', 'Destination')], max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.ride')),
            ],
            options={
                'db_table': 'rides_stop',
            },
        ),
        migrations.CreateModel(
            name='FareConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_fare', models.DecimalField(decimal_places=2, help_text='Base charge for booking / minimum starting charge', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('per_km_rate', models.DecimalField(decimal_places=2, help_text='Charge per kilometer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('per_minute_rate', models.DecimalField(decimal_places=2, help_text='Charge per minute of trip time', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_fare', models.DecimalField(decimal_places=2, help_text='Minimum allowable trip fare', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cancellation_fee', models.DecimalField(decimal_places=2, help_text='Standard fee applied if ride cancelled after threshold', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, help_text='Platform commission percentage between 0 and 100', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('effective_from', models.DateTimeField(help_text='Start timestamp of validity')),
                ('effective_to', models.DateTimeField(blank=True, help_text='End timestamp of validity (null for ongoing)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_configs', to='vehicles.vehiclecategory')),
            ],
            options={
                'db_table': 'rides_fare_config',
                'ordering': ['-effective_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_fare__gte', Decimal('0.00'))), name='fare_config_base_fare_gte_zero'), models.CheckConstraint(condition=models.Q(('per_km_rate__gte', Decimal('0.00'))), name='fare_config_per_km_gte_zero'), models.CheckConstraint(condition=models.Q(('per_minute_rate__gte', Decimal('0.00'))), name='fare_config_per_min_gte_zero'), models.CheckConstraint(condition=models.Q(('minimum_fare__gte', Decimal('0.00'))), name='fare_config_min_fare_gte_zero'), models.CheckConstraint(condition=models.Q(('cancellation_fee__gte', Decimal('0.00'))), name='fare_config_canc_fee_gte_zero'), models.CheckConstraint(condition=models.Q(('platform_commission_percent__gte', Decimal('0.00')), ('platform_commission_percent__lte', Decimal('100.00'))), name='fare_config_commission_0_to_100')],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['customer', 'status', 'created_at'], name='ride_cust_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status', 'created_at'], name='ride_drv_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='ride_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['vehicle_category', 'status', 'created_at'], name='ride_cat_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['created_at'], name='ride_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'ACCEPTED', 'DRIVER_ARRIVED', 'IN_PROGRESS'])), fields=('customer',), name='unique_active_ride_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('driver__isnull', False), ('status__in', ['ACCEPTED', 'DRIVER_ARRIVED', 'IN_PROGRESS'])), fields=('driver',), name='unique_active_ride_per_driver'),
        ),
        migrations.AddConstraint(
            model_name='ridecancellation',
            constraint=models.CheckConstraint(condition=models.Q(('cancellation_charge__gte', Decimal('0.00'))), name='cancellation_charge_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridefare',
            constraint=models.CheckConstraint(condition=models.Q(('base_fare__gte', Decimal('0.00'))), name='fare_base_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridefare',
            constraint=models.CheckConstraint(condition=models.Q(('distance_charge__gte', Decimal('0.00'))), name='fare_distance_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridefare',
            constraint=models.CheckConstraint(condition=models.Q(('duration_charge__gte', Decimal('0.00'))), name='fare_duration_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridefare',
            constraint=models.CheckConstraint(condition=models.Q(('cancellation_charge__gte', Decimal('0.00'))), name='fare_cancellation_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridefare',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', Decimal('0.00'))), name='fare_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridefare',
            constraint=models.CheckConstraint(condition=models.Q(('gross_fare__gte', Decimal('0.00'))), name='fare_gross_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='ridelocationping',
            index=models.Index(fields=['ride', '-recorded_at'], name='ping_ride_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='ridelocationping',
            index=models.Index(fields=['driver', '-recorded_at'], name='ping_driver_rec_idx'),
        ),
        migrations.AddConstraint(
            model_name='ridelocationping',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', Decimal('-90.0')), ('latitude__lte', Decimal('90.0'))), name='ride_ping_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='ridelocationping',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', Decimal('-180.0')), ('longitude__lte', Decimal('180.0'))), name='ride_ping_lon_valid'),
        ),
        migrations.AddConstraint(
            model_name='ridesettlement',
            constraint=models.CheckConstraint(condition=models.Q(('gross_fare__gte', Decimal('0.00'))), name='settlement_gross_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridesettlement',
            constraint=models.CheckConstraint(condition=models.Q(('platform_commission__gte', Decimal('0.00'))), name='settlement_commission_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridesettlement',
            constraint=models.CheckConstraint(condition=models.Q(('driver_net_earnings__gte', Decimal('0.00'))), name='settlement_driver_net_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='ridesettlement',
            constraint=models.CheckConstraint(condition=models.Q(('gross_fare', django.db.models.expressions.CombinedExpression(models.F('platform_commission'), '+', models.F('driver_net_earnings')))), name='settlement_balance_invariant'),
        ),
        migrations.AddConstraint(
            model_name='ridestop',
            constraint=models.UniqueConstraint(fields=('ride', 'stop_type'), name='unique_stop_type_per_ride'),
        ),
        migrations.AddConstraint(
            model_name='ridestop',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', Decimal('-90.0')), ('latitude__lte', Decimal('90.0'))), name='ride_stop_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='ridestop',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', Decimal('-180.0')), ('longitude__lte', Decimal('180.0'))), name='ride_stop_lon_valid'),
        ),
    ]
